# Background

The project titled: “Scientific workflow system for environmental health impact assessments” (https://doi.org/10.47486/PL059) aimed to deliver a scientific workflow system (SWS) for health impact assessments (HIAs) that can be used widely by environmental agencies and industrial organisations to consider the health burden of their policies and activities. 

The work leveraged off the R targets framework to lead toward a standardised computational approach, with alertness to the discourse concerning epidemiological assumptions and limitations. 

The product of our development is explained with user guide at this site https://cardat.github.io/air-health-sws-r-targets/  where a simple step by step user guide can be found with three case studies that meet the research infrastructure (RI) priorities identified during 2021
The codes are all in R and can be accessed at https://github.com/cardat/air-health-sws-r-targets 

## Assumed knowledge

This guidebook assumes some experience with R scripts such as:

- Running R in 'interactive' mode
- Running R functions and some understanding of 'environments'
